# Use postgres/example user/password credentials
version: '3.3'

services:
  db:
    image: postgres
    restart: always
    environment:
#      POSTGRES_DB: budget_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./db-init/insert.sql:/docker-entrypoint-initdb.d/insert-data.sql
      #- db-data:/var/lib/postgresql/data

    ports:
      - 5432:5432
volumes:
  db-data:
    driver: local
